server:
  port: 8080

spring:
  application:
    name: PRODUCT-CRUD

  profiles:
    active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    secret: ${JWT_SECRET:ad64e472322b87f37313725a11920a6752372f9c0247999efebb566532848160}
    expiration: 86400

  liquibase:
    change-log: classpath:db/changelog/master.yaml
