spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-crud-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Virak@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
