server:
  port: 8080

spring:
  application:
    name: PRODUCT-CRUD

  datasource:
    url: jdbc:postgresql://localhost:5432/product-crud-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Virak@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    secret: ${JWT_SECRET:ad64e472322b87f37313725a11920a6752372f9c0247999efebb566532848160}
    expiration: 7

  liquibase:
    change-log: classpath:db/changelog/master.yaml
